### ISSUE TITLE
formadd() segfaults when the value of the argument is an Int.

### ISSUE THREAD

**Issue by tadzik** [CurtTilmes/perl6-libcurl#1]
My minimal testcase:
```
use LibCurl::Easy;

my $req = LibCurl::Easy.new(URL => 'http://localhost');
$req.formadd(name => 'test', contents => 1);
```
Passing the value as "1" works perfectly.

**Comment by CurtTilmes** [comment]
Thank you!

Added a patch to make sure all params are stringified.

https://github.com/CurtTilmes/perl6-libcurl/commit/b5dda296f7848d3c865b12b949e657cbcb045417
