### ISSUE TITLE
MoarVM panic: Internal error: Unwound entire stack and missed handler

### ISSUE THREAD

**Issue by Marcool04** [CurtTilmes/perl6-libcurl#10]
## Expected Behavior
No panic :)

## Actual Behavior
````
$ perl6
To exit type 'exit' or '^D'
> use LibCurl::HTTP;
Nil
> my $browser=LibCurl::HTTP.new;
LibCurl::HTTP.new(handle => LibCurl::EasyHandle.new, header-slist => LibCurl::slist, form => LibCurl::Form, receiveheaders => {}, statusline => Any, upload-fh => NativeCall::Types::Pointer, download-fh => NativeCall::Types::Pointer, sendbuf => Blob, sendindex => Int, buf => Blob, errorbuffer => NativeCall::Types::CArray[uint8].new, debugfunction => Callable, xferinfofunction => Callable, private => Any)
> say $browser.GET("http://google.com").perform.content;
MoarVM panic: Internal error: Unwound entire stack and missed handler
````

## Steps to Reproduce
````
$ zef install LibCurl::HTTP
$ perl6 -MLibCurl::HTTP -e 'my $ua=LibCurl::HTTP.new; say $ua.GET("http://google.com").perform.content;'
MoarVM panic: Internal error: Unwound entire stack and missed handler
````

## Environment
````
$ uname -a
Linux hostname 4.14.49-1-ARCH #1 SMP Fri Jun 15 02:09:36 UTC 2018 armv7l GNU/Linux
$ perl6 -v
This is Rakudo version 2018.05 built on MoarVM version 2018.05
implementing Perl 6.c.
$ pacman -Qi curl
Name            : curl
Version         : 7.60.0-1
Description     : An URL retrieval utility and library
Architecture    : armv7h
URL             : https://curl.haxx.se
Licenses        : MIT
Groups          : None
Provides        : libcurl.so=4-32
````

The machine is a Raspberry Pi 3B1, running ArchLinuxARM, and rakudo was installed using the AUR (Arch User repository) package https://aur.archlinux.org/packages/rakudo/.

I also posted on the [rakudo issue tracker](https://github.com/rakudo/rakudo/issues/1937) as I was not sure what in my previous script was causing it to crash, but now I have picked it apart a little I have narrowed it down to this.
Let me know if you need anything else from me to help debug it.
Best regards,
Mark.

**Comment by MARTIMM** [comment]
I would add that this message is **less than awesome**! In my experience most of the time it's about a wrong type or wrong call to something. It would be a start when there was a mention of what moarvm was looking for. Then, if that is possible, it would be easier for the developer to find his/her bug in the code.

**Comment by Marcool04** [comment]
No longer a bug with:
````
$ pacman -Qi rakudo
Name            : rakudo
Version         : 2019.03.1-1
[clip]
$ zef info LibCurl::HTTP
- Info for: LibCurl::HTTP
- Identity: LibCurl:ver<0.6.1>
````
Sorry for the noise, thanks for the useful module :thumbsup:
