### ISSUE TITLE
FeatureRequest: Let `.content` use the charset specified by the server

### ISSUE THREAD

**Issue by smls** [CurtTilmes/perl6-libcurl#5]
Unless the user specifies something different, the `.content` method currently decodes the response content as `utf-8`.

But HTTP actually has a way for the server to tell us how the content should be interpreted:

    Content-Type: text/html; charset=utf-8

It's cumbersome for users of the module to have to manually parse this after every request.

Any chance the module could do it automatically, and use that charset by default for decoding the content?
It could still fall back to `utf-8` if no `Content-Type` header was received.

**Comment by CurtTilmes** [comment]
Added a patch for this with a basic parser for Content-Type/charset.
