### ISSUE TITLE
fetching binary content

### ISSUE THREAD

**Issue by ufobat** [CurtTilmes/perl6-libcurl#9]
Hello,
I have got a "broken" webserver that offers me a chunk of binary data but unfortunatelly sets this header:
`Content-Type: text/plain;charset=UTF-8`. 
Bechause the $encoding information in the header overrides the $encoding provided in the method call to `content` it is impossible to fetch the data. ( I was assuming that i could decode $random_data with latin1 )

**Comment by CurtTilmes** [comment]
`.content` will decode the incoming data, but you can always get the raw data with `.buf`.

https://github.com/CurtTilmes/perl6-libcurl#content

**Comment by ufobat** [comment]
right, thanks! 
but should the response override the $encoding parameter, if the user specifies one?

**Comment by CurtTilmes** [comment]
The `$encoding` parameter sets a default that is used if the server doesn't tell you its encoding.  I don't think that should change.

With the broken server lying to you, you should a) contact the server's owner and ask them to fix it, and b) just use  `.buf.decode('latin1')` or whatever to decode it however you want.

**Comment by ufobat** [comment]
Allright :) thanks dir your Feedback!
